coxph:
  alpha: 0.1

rsf:
  n_estimators:
    type: "int"
    low: 50
    high: 250
  max_depth:
    type: "int"
    low: 3
    high: 10
  min_samples_split:
    type: "int"
    low: 2
    high: 10
  min_samples_leaf:
    type: "int"
    low: 1
    high: 5

xgb_cox:
  n_estimators:
    type: "int"
    low: 50
    high: 300
  learning_rate:
    type: "float"
    low: 0.01
    high: 0.3
    log: true
  max_depth:
    type: "int"
    low: 3
    high: 8
  subsample:
    type: "float"
    low: 0.6
    high: 1.0
  colsample_bytree:
    type: "float"
    low: 0.6
    high: 1.0
xgb_aft:
  n_estimators: [300]
  learning_rate: [0.05]
  max_depth: [3, 5]
  aft_loss_distribution: ["normal", "logistic"]
  aft_loss_distribution_scale: [1.0, 2.0]
